services:
  db:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: shinrin
      POSTGRES_PASSWORD: shinrin
      POSTGRES_DB: shinrin
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
