import type { ModelProvider } from './modelProviders/modelProvider';
import { getModelProvider } from './modelProviders/providerRegistry';
import { ContextManager, type Message, type ToolCall } from './contextManager';
import type { Tool } from './tools/tool';
import { logger } from './logger';
import { db } from './db/index';
import { sessions } from './db/schema';
import { getOrCreateModel } from './db/getOrCreateModel';
import { getTools, getSubagentTools } from './tools/toolRegistry';
import { extractUserUrls } from './tools/fetchUrlTool';
import type { ModelSelection } from '#lib/models.js';

const MAX_ITERATIONS = 20;
const CANCELLED_MESSAGE = 'Cancelled by user.';
const TRUNCATED_TOOL_CALL_MESSAGE =
	'Not run: the reply hit the output token limit before this tool call was complete, so its ' +
	'arguments may be cut off.';
const INVALID_ARGUMENTS_MESSAGE =
	'Not run: the arguments for this tool call were not valid JSON. Call the tool again with valid ' +
	'JSON arguments.';

export class Agent {
	private provider: ModelProvider;
	private model: string;
	private ctx: ContextManager;
	private tools: Tool[];
	readonly agentId: string;

	constructor(
		agentId: string,
		provider: ModelProvider,
		model: string,
		ctx: ContextManager,
		tools: Tool[] = []
	) {
		this.agentId = agentId;
		this.provider = provider;
		this.model = model;
		this.ctx = ctx;
		// Sorted so the tool list sent to the model is identical on every request regardless of the
		// order the DB returned assignments in — `tools` is the first part of the prompt, so any
		// reordering would invalidate the provider's whole prompt cache.
		this.tools = [...tools].sort((a, b) => a.definition.name.localeCompare(b.definition.name));
	}

	static async create(
		agentId: string,
		name: string,
		selection: ModelSelection,
		parentSessionId?: string
	): Promise<Agent> {
		const agent = await db.query.agents.findFirst({
			where: { id: agentId },
			with: { agentTools: { with: { tool: true } } }
		});

		if (agent === undefined) {
			throw new Error(`Agent with id ${agentId} not found in the database.`);
		}

		const tools = getTools(
			agent.agentTools.map((at) => at.tool.name),
			{
				agentId,
				subjectId: agent.subjectId,
				// A subagent's "prompt" is generated by its calling agent, not typed by a human — it
				// never counts toward fetch_url's URL allowlist, see extractUserUrls.
				urls: []
			}
		);

		const modelId = await getOrCreateModel(selection.provider, selection.name);

		const [session] = await db
			.insert(sessions)
			.values({ agentId, name, modelId, parentSessionId })
			.returning();

		const subagentTools = await getSubagentTools(agentId, selection, session.id);

		const contextManager = new ContextManager(agent.systemPrompt ?? '', session.id);
		const modelProvider = getModelProvider(selection.provider);

		return new Agent(agentId, modelProvider, selection.name, contextManager, [
			...tools,
			...subagentTools
		]);
	}

	static async createFromSession(sessionId: string, prompt: string): Promise<Agent> {
		const session = await db.query.sessions.findFirst({
			where: { id: sessionId },
			with: {
				agent: { with: { agentTools: { with: { tool: true } } } },
				model: { with: { provider: true } }
			}
		});

		if (session === undefined) {
			throw new Error(`Session with id ${sessionId} not found in the database.`);
		}

		const agentId = session.agent.id;
		const selection: ModelSelection = {
			provider: session.model.provider.name as ModelSelection['provider'],
			name: session.model.name
		};

		const systemPrompt = [session.agent.systemPrompt, session.systemPrompt]
			.filter((prompt) => prompt !== null && prompt.trim() !== '')
			.join('\n\n');
		const contextManager = new ContextManager(systemPrompt, session.id);
		await contextManager.load();

		const userTexts = contextManager
			.build()
			.filter((message) => message.role === 'user')
			.map((message) => message.content);
		userTexts.push(prompt);

		const tools = getTools(
			session.agent.agentTools.map((at) => at.tool.name),
			{
				agentId,
				subjectId: session.agent.subjectId,
				urls: extractUserUrls(userTexts)
			}
		);
		const subagentTools = await getSubagentTools(agentId, selection, session.id);
		const modelProvider = getModelProvider(selection.provider);

		return new Agent(agentId, modelProvider, selection.name, contextManager, [
			...tools,
			...subagentTools
		]);
	}

	async compact(): Promise<void> {
		await this.ctx.compact(this.provider, this.model);
	}

	async run(
		prompt: string,
		onChunk: ((delta: string) => void) | undefined,
		signal: AbortSignal
	): Promise<string> {
		const isStreaming = onChunk !== undefined;

		await this.ctx.add({ role: 'user', content: prompt });
		logger.info({ prompt, tools: this.tools.map((t) => t.definition.name) }, 'agent run started');

		let iterations = 0;

		while (iterations < MAX_ITERATIONS) {
			if (signal.aborted) {
				break;
			}

			iterations++;
			logger.debug({ iteration: iterations }, 'agent iteration');

			let response;

			// TODO: not sure about this
			try {
				if (isStreaming) {
					const stream = this.provider.chatStream(this.model, this.ctx.build(), this.tools, signal);
					let next = await stream.next();
					while (!next.done) {
						onChunk(next.value);
						next = await stream.next();
					}
					response = next.value;
				} else {
					response = await this.provider.chat(this.model, this.ctx.build(), this.tools, signal);
				}
			} catch (e) {
				if (signal.aborted) {
					break;
				}
				throw e;
			}

			const toolCalls: ToolCall[] | undefined = response.toolCalls?.map((toolCall) => ({
				id: crypto.randomUUID(),
				...toolCall
			}));
			const hasToolCalls = toolCalls !== undefined && toolCalls.length > 0;
			if (response.content || hasToolCalls) {
				await this.ctx.add({
					role: 'assistant',
					content: response.content,
					toolCalls,
					model: response.model,
					providerContent: response.providerContent
				});
			} else {
				logger.warn(
					{ iteration: iterations, model: this.model },
					'model returned neither content nor tool calls — retrying'
				);
				await this.ctx.add({
					role: 'system',
					content: 'Provided no response, and called no tools. Retry.'
				});
				continue;
			}
			logger.debug({ content: response.content, toolCalls }, 'model response');

			if (toolCalls !== undefined) {
				for (const toolCall of toolCalls) {
					if (signal.aborted) {
						break;
					}

					logger.info({ tool: toolCall.name, args: toolCall.args }, 'tool call');
					const tool = this.tools.find((t) => t.definition.name === toolCall.name);
					let result;
					if (response.truncated) {
						result = TRUNCATED_TOOL_CALL_MESSAGE;
						logger.warn({ tool: toolCall.name }, 'tool call truncated by output token limit');
					} else if (toolCall.invalidArguments) {
						result = INVALID_ARGUMENTS_MESSAGE;
						logger.warn({ tool: toolCall.name }, 'tool call arguments were not valid JSON');
					} else if (tool) {
						try {
							result = await tool.execute(toolCall.args, signal);
							logger.debug({ tool: toolCall.name, result }, 'tool result');
						} catch (e) {
							if (signal.aborted) {
								result = CANCELLED_MESSAGE;
								logger.info({ tool: toolCall.name }, 'tool cancelled');
							} else {
								// Any Error's message, not just ToolError's — JSON.stringify(error) is "{}", which
								// hid real failures (e.g. a subagent's missing API key) from the model and the logs.
								result = e instanceof Error ? e.message : String(e);
								logger.error({ tool: toolCall.name, error: result }, 'tool error');
							}
						}
					} else {
						// Still answered, so the call has a result like any other — the model sees why
						// nothing happened instead of a call that silently went nowhere.
						result = `Tool not found: ${toolCall.name}`;
						logger.warn({ tool: toolCall.name }, 'tool not found');
					}

					const toolMessage: Message = {
						role: 'tool',
						content: result,
						toolName: toolCall.name,
						toolCallId: toolCall.id
					};
					await this.ctx.add(toolMessage);
				}
				if (signal.aborted) {
					break;
				}

				// The calls were answered above (so the history stays valid), but not run — end here with
				// whatever text the reply had, rather than looping into a retry that would likely hit the
				// same limit.
				if (response.truncated) {
					logger.warn('agent run ended: reply hit the output token limit');
					return response.content;
				}

				continue;
			}

			logger.info('agent run completed');
			return response.content;
		}

		if (signal.aborted) {
			logger.info('agent run cancelled');
			await this.ctx.add({ role: 'assistant', content: CANCELLED_MESSAGE });
			return CANCELLED_MESSAGE;
		}

		logger.warn({ maxIterations: MAX_ITERATIONS }, 'max iterations reached');
		return 'Maximum iterations reached without completing task';
	}
}
